# Generated by Django 4.2.3 on 2023-07-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.gender'),
        ),
    ]
